# Generated by Django 3.1.4 on 2020-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='back_stock',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ro',
            field=models.CharField(default='romanian', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='russian', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
